name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# env:
#   DB_PATH: ./db.sqlite

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'yarn'
    - run: yarn --immutable
    - run: yarn lint
  tests:
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        tests:
          - polkadot/src/acala.moonbeam.test.ts
          - polkadot/src/acala.polkadot.test.ts
          - polkadot/src/assetHubPolkadot.acala.test.ts
          - polkadot/src/polkadot.astar.test.ts
          - kusama/src/basilisk.karura.test.ts
          - kusama/src/karura.assetHubKusama.test.ts
          - kusama/src/kusamakarura.test.ts
          - kusama/src/karura.shiden.test.ts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Setup yarn
      run: npm install -g yarn
    - name: setup node env
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'yarn'
    - run: yarn --immutable
    - run: yarn update-env
    - run: yarn test packages/${{ matrix.tests }}
